import type { Metadata } from "next";
import { manrope } from "@/utils";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Introduce from "./introduce/introduce";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={manrope.className}>
            <Header/>           
            <main>{children}</main>   
            <Introduce></Introduce>
            <Footer/>
      </body>
    </html>
  );
}
