import type { Metadata } from "next";
import { manrope } from "@/utils";
import "/styles/globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const pathname = usePathname(); // Lấy đường dẫn hiện tại

  // Kiểm tra nếu là trang admin, dùng AdminLayout, ngược lại dùng ClientLayout
  const isAdmin = pathname.startsWith("/admin");

  return (
    <html lang="en">
      <body className={manrope.className}>
        {isAdmin ? <AdminLayout>{children}</AdminLayout> : <ClientLayout>{children}</ClientLayout>}
      </body>
    </html>
  );
}
